# Generated by Django 4.1.9 on 2023-06-15 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('professor', models.CharField(choices=[('Orlando', 'ORLANDO SARAIVA JR'), ('Nilton', 'NILTON SACCO'), ('Joao', 'JOAO NETO')], default='Orlando', max_length=100, verbose_name='professor')),
                ('data', models.DateField(default=datetime.datetime(2023, 6, 15, 0, 43, 3, 499456, tzinfo=datetime.timezone.utc), verbose_name='Data')),
            ],
            options={
                'verbose_name_plural': 'Aluno',
            },
        ),
    ]
