# Generated by Django 4.1.9 on 2023-06-15 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromodel',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 0, 43, 11, 596515, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
    ]
