# Generated by Django 4.1.9 on 2023-06-15 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cadastromodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromodel',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 0, 46, 47, 959353, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
    ]
